# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FDDqX3gplfRNp_0ZqXthZ5hp4hhxtrOj
"""

for i in range(5,1,-1):
  print(i)

x = int(input("Enter number to calculate the table: "))
for i in range(1 , 11):
  print(x , "x" , i , "=" , x*i)

